/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SynonymerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// settings.ts
var DEFAULT_SETTINGS = {
  enableOnlineLookup: true,
  apiSource: "thesaurus_com",
  apiKey: "",
  maxSynonyms: 10,
  selectedLanguage: "en_US"
};

// synonymService.ts
var import_obsidian = require("obsidian");
var SynonymService = class {
  constructor(settings, assetDictionary, customManager) {
    this.settings = settings;
    this.assetDictionary = {};
    this.customManager = null;
    if (assetDictionary) {
      this.assetDictionary = assetDictionary;
    }
    if (customManager) {
      this.customManager = customManager;
    }
  }
  async getSynonyms(word) {
    const customSynonyms = this.getCustomSynonyms(word);
    const assetSynonyms = this.getAssetSynonyms(word);
    const localSynonyms = this.getLocalSynonyms(word);
    const allLocalSynonyms = [
      ...customSynonyms,
      ...assetSynonyms,
      ...localSynonyms.filter((s) => !assetSynonyms.includes(s))
    ];
    const filteredLocal = allLocalSynonyms;
    if (filteredLocal.length > 0 && !this.settings.enableOnlineLookup) {
      return filteredLocal.slice(0, this.settings.maxSynonyms);
    }
    try {
      const onlineSynonyms = await this.getOnlineSynonyms(word);
      const combined = [
        ...customSynonyms,
        ...onlineSynonyms.filter((s) => !customSynonyms.includes(s)),
        ...filteredLocal.filter((s) => !customSynonyms.includes(s) && !onlineSynonyms.includes(s))
      ];
      if (combined.length > 0) {
        return combined.slice(0, this.settings.maxSynonyms);
      }
      return filteredLocal.slice(0, this.settings.maxSynonyms);
    } catch (error) {
      console.error("Error fetching online synonyms:", error);
      if (filteredLocal.length > 0) {
        return filteredLocal.slice(0, this.settings.maxSynonyms);
      }
      throw new Error(`Could not fetch synonyms: ${error instanceof Error ? error.message : "Network error"}`);
    }
  }
  getCustomSynonyms(word) {
    if (!this.customManager)
      return [];
    return this.customManager.getSynonyms(word);
  }
  getAssetSynonyms(word) {
    const normalizedWord = word.toLowerCase().trim();
    return this.assetDictionary[normalizedWord] || [];
  }
  getLocalSynonyms(word) {
    return [];
  }
  async getOnlineSynonyms(word) {
    if (this.settings.apiSource === "thesaurus_com") {
      return await this.getSynonymsFromThesaurusCom(word);
    } else if (this.settings.apiSource === "svenska_se") {
      const synonymerResults = await this.getSynonymsFromSynonymerSe(word);
      if (synonymerResults.length >= this.settings.maxSynonyms) {
        return synonymerResults;
      }
      const svenskaResults = await this.getSynonymsFromSvenskaSe(word);
      const combined = [...synonymerResults, ...svenskaResults];
      return [...new Set(combined)];
    } else {
      return await this.getSynonymsFromThesaurusCom(word);
    }
  }
  async getSynonymsFromSvenskaSe(word) {
    try {
      const url = `https://www.synonymlexikon.se/sv-syn/${encodeURIComponent(word.toLowerCase())}`;
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const synonymPattern = /<li class="synonym-item">.*?>(.*?)<\/a>/gi;
        let match;
        while ((match = synonymPattern.exec(html)) !== null) {
          if (match[1]) {
            const synonym = match[1].trim();
            if (synonym.toLowerCase() !== word.toLowerCase()) {
              synonyms.push(synonym);
            }
          }
        }
        if (synonyms.length === 0) {
          const altPattern = /<dd class="word">(.*?)<\/dd>/gi;
          while ((match = altPattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase()) {
                synonyms.push(synonym);
              }
            }
          }
        }
        if (synonyms.length > 0) {
          return [...new Set(synonyms)];
        }
      }
    } catch (error) {
      console.error("Error with synonymlexikon.se:", error);
    }
    console.log("Synonymlexikon attempts completed");
    return [];
  }
  async getSynonymsFromSynonymerSe(word) {
    try {
      const url = `https://www.synonymer.se/sv-syn/${encodeURIComponent(word.toLowerCase())}`;
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const mainPattern = /<div[^>]*class="main"[^>]*>([\s\S]*?)<\/div>/gi;
        let mainMatch;
        while ((mainMatch = mainPattern.exec(html)) !== null) {
          if (mainMatch[1]) {
            const synonymPattern = /<a[^>]*>([^<]+)<\/a>/gi;
            let match;
            while ((match = synonymPattern.exec(mainMatch[1])) !== null) {
              if (match[1]) {
                const synonym = match[1].trim();
                if (synonym.toLowerCase() !== word.toLowerCase() && !synonym.startsWith("/") && synonym.length > 1) {
                  synonyms.push(synonym);
                }
              }
            }
          }
        }
        if (synonyms.length === 0) {
          const patterns = [
            /<span class="word"[^>]*>([^<]+)<\/span>/gi,
            /<a href="\/sv-syn\/[^"]+"[^>]*>([^<]+)<\/a>/gi,
            /<td class="word"[^>]*>([^<]+)<\/td>/gi
          ];
          for (const pattern of patterns) {
            let match;
            while ((match = pattern.exec(html)) !== null) {
              if (match[1]) {
                const synonym = match[1].trim();
                if (synonym.toLowerCase() !== word.toLowerCase() && !synonym.startsWith("/") && synonym.length > 1) {
                  synonyms.push(synonym);
                }
              }
            }
          }
        }
        if (synonyms.length > 0) {
          return [...new Set(synonyms)];
        }
      }
      console.log(`Failed with status: ${response.status}`);
    } catch (error) {
      console.error("Error with synonymer.se:", error);
    }
    return [];
  }
  async getSynonymsFromThesaurusCom(word) {
    try {
      const url = `https://www.thesaurus.com/browse/${encodeURIComponent(word.toLowerCase())}`;
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<div[^>]*data-testid="word-grid-container"[^>]*>([\s\S]*?)<\/div>/gi,
          /<a[^>]*href="\/browse\/([^"]+)"[^>]*>([^<]+)<\/a>/gi,
          /<section[^>]*id="[^"]*synonym[^"]*"[^>]*>([\s\S]*?)<\/section>/gi,
          /<ul[^>]*class="[^"]*synonym[^"]*"[^>]*>([\s\S]*?)<\/ul>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            const content = match[1] || match[2] || "";
            const linkPattern = /<a[^>]*>([^<]+)<\/a>/gi;
            let linkMatch;
            while ((linkMatch = linkPattern.exec(content)) !== null) {
              const synonym = linkMatch[1].trim();
              if (synonym && synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && synonym.length < 30 && !/^\d+$/.test(synonym) && !synonym.includes("...")) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Thesaurus.com:", error);
    }
    return [];
  }
  async getSynonymsFromSynonymsNet(word) {
    try {
      const url = `https://www.synonyms.net/synonym/${encodeURIComponent(word.toLowerCase())}`;
      console.log(`Trying Synonyms.net: ${url}`);
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<div class="syn">([^<]+)<\/div>/gi,
          /<a[^>]*href="\/synonym\/[^"]*"[^>]*>([^<]+)<\/a>/gi,
          /<li[^>]*>([^<]+)<\/li>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && !synonym.includes("http") && !/^\d+$/.test(synonym)) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          console.log(`Found ${synonyms.length} synonyms from Synonyms.net`);
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Synonyms.net:", error);
    }
    return [];
  }
  async getSynonymsFromSynonymeDe(word) {
    try {
      const url = `https://www.synonyme.de/${encodeURIComponent(word.toLowerCase())}/`;
      console.log(`Trying Synonyme.de: ${url}`);
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<a[^>]*href="\/[^"]*"[^>]*>([^<]+)<\/a>/gi,
          /<span[^>]*class="[^"]*syn[^"]*"[^>]*>([^<]+)<\/span>/gi,
          /<li[^>]*>([^<]+)<\/li>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && !synonym.includes("http") && !/^\d+$/.test(synonym)) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          console.log(`Found ${synonyms.length} synonyms from Synonyme.de`);
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Synonyme.de:", error);
    }
    return [];
  }
  async getSynonymsFromSynonymesFr(word) {
    try {
      const url = `https://www.synonymes.com/synonyme.php?mot=${encodeURIComponent(word.toLowerCase())}`;
      console.log(`Trying Synonymes.com: ${url}`);
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<a[^>]*href="synonyme\.php\?mot=[^"]*"[^>]*>([^<]+)<\/a>/gi,
          /<a[^>]*href="\/synonyme\/[^"]*"[^>]*>([^<]+)<\/a>/gi,
          /<span[^>]*class="[^"]*syn[^"]*"[^>]*>([^<]+)<\/span>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && !synonym.includes("http")) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          console.log(`Found ${synonyms.length} synonyms from Synonymes.com`);
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Synonymes.com:", error);
    }
    return [];
  }
  async getSynonymsFromSinonimosEs(word) {
    try {
      const url = `https://www.sinonimos.com/${encodeURIComponent(word.toLowerCase())}/`;
      console.log(`Trying Sinonimos.com: ${url}`);
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<a[^>]*href="\/[^"]*\/"[^>]*>([^<]+)<\/a>/gi,
          /<span[^>]*class="[^"]*sin[^"]*"[^>]*>([^<]+)<\/span>/gi,
          /<li[^>]*class="[^"]*"[^>]*>([^<]+)<\/li>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && !synonym.includes("http") && !/^\d+$/.test(synonym)) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          console.log(`Found ${synonyms.length} synonyms from Sinonimos.com`);
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Sinonimos.com:", error);
    }
    return [];
  }
  async getSynonymsFromSinonimosPt(word) {
    try {
      const url = `https://www.sinonimos.com.br/${encodeURIComponent(word.toLowerCase())}/`;
      console.log(`Trying Sinonimos.com.br: ${url}`);
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<a[^>]*href="\/[^"]*\/"[^>]*>([^<]+)<\/a>/gi,
          /<span[^>]*class="[^"]*sin[^"]*"[^>]*>([^<]+)<\/span>/gi,
          /<li[^>]*>([^<]+)<\/li>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && !synonym.includes("http") && !/^\d+$/.test(synonym)) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          console.log(`Found ${synonyms.length} synonyms from Sinonimos.com.br`);
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Sinonimos.com.br:", error);
    }
    return [];
  }
  async getSynonymsFromSinonimiIt(word) {
    try {
      const url = `https://www.sinonimi.org/sinonimi/${encodeURIComponent(word.toLowerCase())}.html`;
      console.log(`Trying Sinonimi.org: ${url}`);
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "Accept": "text/html",
          "User-Agent": "Mozilla/5.0 (compatible; ObsidianSynonymPlugin/1.0)"
        },
        throw: false
      });
      if (response.status === 200) {
        const html = response.text;
        const synonyms = [];
        const patterns = [
          /<a[^>]*href="\/sinonimi\/[^"]*"[^>]*>([^<]+)<\/a>/gi,
          /<a[^>]*href="[^"]*"[^>]*>([^<]+)<\/a>/gi,
          /<li[^>]*>([^<]+)<\/li>/gi
        ];
        for (const pattern of patterns) {
          let match;
          while ((match = pattern.exec(html)) !== null) {
            if (match[1]) {
              const synonym = match[1].trim();
              if (synonym.toLowerCase() !== word.toLowerCase() && synonym.length > 1 && !synonym.includes("http") && !/^\d+$/.test(synonym)) {
                synonyms.push(synonym);
              }
            }
          }
          if (synonyms.length > 0)
            break;
        }
        if (synonyms.length > 0) {
          console.log(`Found ${synonyms.length} synonyms from Sinonimi.org`);
          return [...new Set(synonyms)].slice(0, 20);
        }
      }
    } catch (error) {
      console.error("Error with Sinonimi.org:", error);
    }
    return [];
  }
};

// assetDictionaryLoader.ts
var import_obsidian2 = require("obsidian");
var AssetDictionaryLoader = class {
  constructor(app, pluginDir) {
    this.app = app;
    this.vault = app.vault;
    this.basePath = (0, import_obsidian2.normalizePath)(`${pluginDir}/assets`);
  }
  async loadDictionary(languageCode) {
    if (languageCode === "sv_SE") {
      const xmlPath = (0, import_obsidian2.normalizePath)(`${this.basePath}/Synlex.xml`);
      try {
        const fileContent = await this.app.vault.adapter.read(xmlPath);
        return this.parseSynlexXml(fileContent);
      } catch (error) {
      }
    }
    const fileName = `th_${languageCode}_v2.dat`;
    const filePath = (0, import_obsidian2.normalizePath)(`${this.basePath}/${fileName}`);
    try {
      const fileContent = await this.app.vault.adapter.read(filePath);
      return this.parseDatFile(fileContent);
    } catch (error) {
      console.error(`Error loading dictionary from ${filePath}:`, error);
      return {};
    }
  }
  parseSynlexXml(content) {
    const dictionary = {};
    const synPattern = /<syn level="([\d.]+)">\s*<w1>(.*?)<\/w1>\s*<w2>(.*?)<\/w2>\s*<\/syn>/g;
    let match;
    let pairCount = 0;
    while ((match = synPattern.exec(content)) !== null) {
      const level = parseFloat(match[1]);
      const word1 = match[2].trim().toLowerCase();
      const word2 = match[3].trim().toLowerCase();
      if (level >= 3 && word1 && word2) {
        if (!dictionary[word1]) {
          dictionary[word1] = [];
        }
        if (!dictionary[word1].includes(word2)) {
          dictionary[word1].push(word2);
        }
        if (!dictionary[word2]) {
          dictionary[word2] = [];
        }
        if (!dictionary[word2].includes(word1)) {
          dictionary[word2].push(word1);
        }
        pairCount++;
      }
    }
    return dictionary;
  }
  parseDatFile(content) {
    var _a, _b;
    const dictionary = {};
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = (_a = lines[i]) == null ? void 0 : _a.trim();
      if (!line)
        continue;
      const parts = line.split("|");
      if (parts.length < 2)
        continue;
      const word = parts[0].toLowerCase().trim();
      if (!word)
        continue;
      const secondPart = parts[1].trim();
      if (/^\d+$/.test(secondPart)) {
        i++;
        if (i >= lines.length)
          break;
        const synonymLine = (_b = lines[i]) == null ? void 0 : _b.trim();
        if (!synonymLine)
          continue;
        const synonyms = synonymLine.replace(/^\|/, "").split("|").map((s) => {
          return s.replace(/\([^)]*\)/g, "").trim();
        }).filter((s) => s.length > 0 && s !== word);
        if (synonyms.length > 0) {
          dictionary[word] = synonyms;
        }
      } else {
        const synonyms = parts.slice(1).map((s) => {
          return s.replace(/\([^)]*\)/g, "").trim();
        }).filter((s) => s.length > 0 && s !== word && !/^\d+$/.test(s));
        if (synonyms.length > 0) {
          dictionary[word] = synonyms;
        }
      }
    }
    return dictionary;
  }
  async getAvailableLanguages() {
    const languages = [];
    try {
      const datPattern = /th_([^_]+_[^_]+)_v2\.dat$/;
      const files = await this.app.vault.adapter.list(this.basePath);
      for (const file of files.files) {
        const fileName = file.split("/").pop() || file.split("\\").pop() || file;
        if (fileName === "Synlex.xml") {
          languages.push("sv_SE");
        }
      }
      for (const file of files.files) {
        const fileName = file.split("/").pop() || file.split("\\").pop() || file;
        const match = fileName.match(datPattern);
        if (match && match[1]) {
          if (match[1] !== "sv_SE" || !languages.includes("sv_SE")) {
            languages.push(match[1]);
          }
        }
      }
    } catch (error) {
      console.error("Error scanning for language files:", error);
    }
    return languages;
  }
};

// customDictionaryManager.ts
var import_obsidian3 = require("obsidian");
var CustomDictionaryManager = class {
  constructor(app, pluginDir) {
    this.dictionary = {};
    var _a, _b, _c;
    this.app = app;
    this.vault = app.vault;
    const settings = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.synonym) == null ? void 0 : _c.settings;
    const lang = (settings == null ? void 0 : settings.selectedLanguage) || "en";
    this.filePath = (0, import_obsidian3.normalizePath)(`${pluginDir}/assets/custom-synonyms-${lang}.json`);
  }
  async load() {
    try {
      try {
        const content = await this.app.vault.adapter.read(this.filePath);
        this.dictionary = JSON.parse(content);
        return this.dictionary;
      } catch (readError) {
        this.dictionary = {};
        return {};
      }
    } catch (error) {
      console.error("Error loading custom dictionary:", error);
      this.dictionary = {};
      return {};
    }
  }
  async save(dictionary) {
    if (dictionary !== void 0) {
      this.dictionary = dictionary;
    }
    try {
      const content = JSON.stringify(this.dictionary, null, 2);
      await this.app.vault.adapter.write(this.filePath, content);
    } catch (error) {
      console.error("Error saving custom dictionary:", error);
      throw error;
    }
  }
  async addSynonym(word, synonym) {
    const normalizedWord = word.toLowerCase().trim();
    const normalizedSynonym = synonym.trim();
    if (!this.dictionary[normalizedWord]) {
      this.dictionary[normalizedWord] = [];
    }
    if (!this.dictionary[normalizedWord].includes(normalizedSynonym)) {
      this.dictionary[normalizedWord].push(normalizedSynonym);
      await this.save();
    }
  }
  async removeSynonym(word, synonym) {
    const normalizedWord = word.toLowerCase().trim();
    if (this.dictionary[normalizedWord]) {
      this.dictionary[normalizedWord] = this.dictionary[normalizedWord].filter((s) => s !== synonym);
      if (this.dictionary[normalizedWord].length === 0) {
        delete this.dictionary[normalizedWord];
      }
      await this.save();
    }
  }
  getSynonyms(word) {
    const normalizedWord = word.toLowerCase().trim();
    return this.dictionary[normalizedWord] || [];
  }
  getAllWords() {
    return Object.keys(this.dictionary).sort();
  }
  async openFile() {
    try {
      const fileExists = await this.app.vault.adapter.exists(this.filePath);
      if (!fileExists) {
        await this.save();
      }
      let file = this.app.vault.getAbstractFileByPath(this.filePath);
      if (!file) {
        await this.app.vault.adapter.stat(this.filePath);
        await new Promise((resolve) => setTimeout(resolve, 500));
        file = this.app.vault.getAbstractFileByPath(this.filePath);
      }
      if (file instanceof import_obsidian3.TFile) {
        const leaf = this.app.workspace.getLeaf("tab");
        await leaf.openFile(file);
      } else {
        console.error("Unable to open file - not recognized as TFile by vault");
        throw new Error("Unable to open custom synonyms file. Please navigate to it manually in the file explorer.");
      }
    } catch (error) {
      console.error("Error opening custom synonyms file:", error);
      throw error;
    }
  }
};

// main.ts
var AddSynonymModal = class extends import_obsidian4.Modal {
  constructor(app, word, onSubmit) {
    super(app);
    this.word = word;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: `Add synonym for "${this.word}"` });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "Enter synonym..."
    });
    inputEl.style.width = "100%";
    inputEl.style.marginBottom = "10px";
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "10px";
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const submitBtn = buttonContainer.createEl("button", {
      text: "Add",
      cls: "mod-cta"
    });
    submitBtn.onclick = () => {
      const synonym = inputEl.value.trim();
      if (synonym) {
        this.onSubmit(synonym);
        this.close();
      }
    };
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        const synonym = inputEl.value.trim();
        if (synonym) {
          this.onSubmit(synonym);
          this.close();
        }
      }
    });
    inputEl.focus();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var SynonymerPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    this.addStyles();
    await this.loadSettings();
    this.customManager = new CustomDictionaryManager(this.app, this.manifest.dir);
    await this.customManager.load();
    const assetLoader = new AssetDictionaryLoader(this.app, this.manifest.dir);
    const assetDict = await assetLoader.loadDictionary(this.settings.selectedLanguage);
    this.synonymService = new SynonymService(this.settings, assetDict, this.customManager);
    this.addRibbonIcon("clipboard-list", "Synonym", (evt) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
      if (view) {
        const editor = view.editor;
        const selection = editor.getSelection();
        if (selection) {
          this.showSynonyms(selection, editor);
        } else {
          new import_obsidian4.Notice("Select a word to find synonyms");
        }
      } else {
        new import_obsidian4.Notice("This feature only works in Markdown view");
      }
    });
    this.addCommand({
      id: "show-synonyms",
      name: "Show synonyms for selected word",
      editorCallback: (editor, ctx) => {
        if (ctx instanceof import_obsidian4.MarkdownView) {
          const selection = editor.getSelection();
          if (selection) {
            this.showSynonyms(selection, editor);
          } else {
            new import_obsidian4.Notice("Select a word to find synonyms");
          }
        } else {
          new import_obsidian4.Notice("This feature only works in Markdown view");
        }
      }
    });
    this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor) => {
      let selection = editor.getSelection();
      if (!selection || selection.trim() === "") {
        selection = this.getWordAtCursor(editor);
      }
      if (selection && selection.trim() !== "") {
        menu.addItem((item) => {
          item.setTitle("L\xE4gg till synonym").setIcon("pencil").onClick(() => {
            this.promptAddSynonym(selection);
          });
        });
        menu.addItem((item) => {
          item.setTitle("Hitta synonymer").setIcon("search").onClick(() => {
            this.showSynonyms(selection, editor);
          });
        });
      }
    }));
    this.addSettingTab(new SynonymerSettingTab(this.app, this));
  }
  getWordAtCursor(editor) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    let start = cursor.ch;
    let end = cursor.ch;
    const wordChar = /[\w\u00C0-\u00ff\-]/;
    while (start > 0 && wordChar.test(line.charAt(start - 1))) {
      start--;
    }
    while (end < line.length && wordChar.test(line.charAt(end))) {
      end++;
    }
    return line.slice(start, end);
  }
  async promptAddSynonym(word) {
    new AddSynonymModal(this.app, word, async (synonym) => {
      try {
        await this.customManager.addSynonym(word, synonym);
        const assetLoader = new AssetDictionaryLoader(this.app, this.manifest.dir);
        const assetDict = await assetLoader.loadDictionary(this.settings.selectedLanguage);
        this.synonymService = new SynonymService(this.settings, assetDict, this.customManager);
        new import_obsidian4.Notice(`Added "${synonym}" as a synonym for "${word}"`);
      } catch (error) {
        console.error("Error adding synonym:", error);
        new import_obsidian4.Notice("Could not add synonym: " + (error instanceof Error ? error.message : "Unknown error"));
      }
    }).open();
  }
  addStyles() {
    const styleEl = document.createElement("style");
    styleEl.id = "synonym-plugin-styles";
    styleEl.textContent = `
			/* Synonym Plugin Custom Styles */
			.synonymer-menu-item {
			  padding: 8px 12px;
			  cursor: pointer;
			  display: flex;
			  align-items: center;
			  font-size: 14px;
			  width: 100%;
			  text-align: left;
			}
			
			.synonymer-menu-item:hover {
			  background-color: var(--background-modifier-hover);
			  color: var(--text-accent);
			}
			
			.synonymer-notice {
			  font-size: 14px;
			  padding: 8px;
			  background-color: var(--background-primary);
			  border-left: 4px solid var(--text-accent);
			  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
			}
			
			/* Make the toolbar icon black and white */
			.side-dock-ribbon-action[aria-label="Synonym"] svg {
			  color: var(--icon-color) !important;
			}
		`;
    document.head.appendChild(styleEl);
  }
  async showSynonyms(word, editor) {
    try {
      new import_obsidian4.Notice(`Searching for synonyms for "${word}"...`, 2e3);
      const synonyms = await this.synonymService.getSynonyms(word);
      if (synonyms.length === 0) {
        new import_obsidian4.Notice(`No synonyms found for "${word}"`, 3e3);
        return;
      }
      const menu = this.createSynonymMenu(synonyms, (synonym) => {
        editor.replaceSelection(synonym);
      });
      let rect;
      try {
        const selection = window.getSelection();
        if (selection && selection.rangeCount > 0) {
          const range = selection.getRangeAt(0);
          const domRect = range.getBoundingClientRect();
          rect = { left: domRect.left, bottom: domRect.bottom };
        } else {
          throw new Error("No selection ranges available");
        }
      } catch (e) {
        const pos = editor.getCursor();
        const lineHeight = 20;
        rect = {
          left: 100,
          bottom: 200 + (pos.line + 1) * lineHeight
        };
      }
      menu.showAtPosition({ x: rect.left, y: rect.bottom });
    } catch (error) {
      console.error("Error fetching synonyms:", error);
      let errorMessage;
      if (error instanceof Error) {
        if (error.message.includes("ERR_NAME_NOT_RESOLVED") || error.message.includes("ERR_CONNECTION_REFUSED") || error.message.includes("NetworkError")) {
          errorMessage = "Could not connect to the synonym service. Check your internet connection.";
        } else {
          errorMessage = error.message;
        }
      } else {
        errorMessage = "Unknown error";
      }
      new import_obsidian4.Notice(`Could not fetch synonyms: ${errorMessage}`, 4e3);
    }
  }
  createSynonymMenu(synonyms, onSelect) {
    const menu = new import_obsidian4.Menu();
    menu.addItem((item) => {
      item.setTitle(`Found ${synonyms.length} synonyms:`).setDisabled(true);
    });
    menu.addSeparator();
    if (synonyms.length > 10) {
      const submenuSize = Math.ceil(synonyms.length / 2);
      const firstHalf = synonyms.slice(0, submenuSize);
      const secondHalf = synonyms.slice(submenuSize);
      firstHalf.forEach((synonym) => {
        menu.addItem((item) => {
          item.setTitle(synonym).onClick(() => onSelect(synonym));
        });
      });
      if (secondHalf.length > 0) {
        menu.addSeparator();
        secondHalf.forEach((synonym) => {
          menu.addItem((item) => {
            item.setTitle(synonym).onClick(() => onSelect(synonym));
          });
        });
      }
    } else {
      synonyms.forEach((synonym) => {
        menu.addItem((item) => {
          item.setTitle(synonym).onClick(() => onSelect(synonym));
        });
      });
    }
    return menu;
  }
  onunload() {
    const styleEl = document.getElementById("synonym-plugin-styles");
    if (styleEl)
      styleEl.remove();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SynonymerSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Synonym Settings" });
    new import_obsidian4.Setting(containerEl).setName("Dictionary language").setDesc("Select the language for the local synonym dictionary").addDropdown(async (dropdown) => {
      const loader = new AssetDictionaryLoader(this.app, this.plugin.manifest.dir);
      const languages = await loader.getAvailableLanguages();
      if (languages.length === 0) {
        dropdown.addOption("", "No dictionaries found");
      } else {
        languages.forEach((lang) => {
          dropdown.addOption(lang, lang);
        });
      }
      dropdown.setValue(this.plugin.settings.selectedLanguage).onChange(async (value) => {
        this.plugin.settings.selectedLanguage = value;
        await this.plugin.saveSettings();
        new import_obsidian4.Notice("Reload the plugin to use the new language");
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Enable online lookup").setDesc("Search for additional synonyms from online sources to complement local dictionary").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableOnlineLookup).onChange(async (value) => {
      this.plugin.settings.enableOnlineLookup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Online source").setDesc("Select which online service to use for additional synonyms").addDropdown((dropdown) => dropdown.addOption("thesaurus_com", "Thesaurus.com (English)").addOption("svenska_se", "Synonymer (Swedish)").setValue(this.plugin.settings.apiSource).onChange(async (value) => {
      this.plugin.settings.apiSource = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("API key").setDesc("API key for online service (if required by the selected source)").addText((text) => text.setPlaceholder("Enter API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Maximum synonyms").setDesc("Maximum number of synonyms to display").addSlider((slider) => slider.setLimits(3, 25, 1).setValue(this.plugin.settings.maxSynonyms).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxSynonyms = value;
      await this.plugin.saveSettings();
    }));
  }
};
